initial commit, faq on dask and parallelization
Ouranosinc/pavics-sdi pull request #340
Opened 2024-11-20 17:07 UTC by aslibese

2025-01-06 16:45 UTC, tlogan2000 requested changes
This is really great made a few suggestions for the initial sections

2025-01-21 14:59 UTC, huard commented
I really like the notebook. It's clearly written and provides solutions to typical issues we face. 

My suggestions are to
- keep the runtime short for all cells, so the nb can be tested and edited quickly;
- only display cell outputs relevant to the discussion;
- keep the examples as conceptually simple as possible to focus on the main concepts; 
- address very technical optimization discussions in a separate section (e.g. Optimization tips)

2025-01-27 23:11 UTC, aslibese commented
<p>Reduced the cell outputs. I kept the headers in case the reader wants to run a cell by itself or copy it to their personal notebook</p>

---

 <a href='https://app.reviewnb.com/Ouranosinc/pavics-sdi/pull/340/discussion/#comment-2604950075'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2025-01-27 23:18 UTC, aslibese commented
Hi @huard, thank you so much for a thorough review. I incorporated all your feedback and marked them as resolved. The only part I kept is the headers in each code cell in case the reader wants to run it separately or we decide to split the notebook into separate sub-sections. Let me know if you have any additional feedback.

2025-01-31 19:07 UTC, huard commented
Okay, this makes sense. nothing to add for now.

2025-01-31 19:54 UTC, tlogan2000 approved these changes
@huard from your last comment I think I can approve the PR and @aslibese  can merge...

2025-01-31 19:56 UTC, merged

2025-02-06 18:00 UTC, tlvu commented
This new notebook takes 30 minutes to run !   Do we really want our users to wait that long when they try the notebook?  Maybe they will think the notebook is just hanging.

Also this is massively increasing the Jenkins runs duration.

Could we use smaller examples to cap the entire notebook execution time to 2-3 minutes instead?